# Minimum Supported Rust Version (conservative for WASM tooling)
msrv = "1.80"
# Complexity thresholds (stricter for WASM due to size concerns)
cognitive-complexity-threshold = 20
too-many-arguments-threshold   = 6
type-complexity-threshold      = 150
# API stability (important for JS interop)
avoid-breaking-exported-api = true
# WASM-specific considerations
missing-docs-in-crate-items = false
# Additional lints useful for WASM
disallowed-methods = [] # Add methods you want to avoid in WASM context
# Size thresholds
pass-by-value-size-limit = 256
trivial-copy-size-limit  = 64
# Other useful settings
max-fn-params-bools                 = 3
max-trait-bounds                    = 3
single-char-binding-names-threshold = 4
